import { AbsoluteFill, BowedString, DeskTap, Easing, FeltPiano, Img, Mallet, Tone, Typing, Typewriter, interpolate, progress, staticFile, useFrame } from "@clapper/core";
import { Dot, LockGlyph, Wordmark } from "./ui";

export const INTERN_FILM_DURATION = 1140;
const C = { ink: "#1b1811", muted: "#676154", line: "#dfded7", paper: "#fff", wash: "#f3f2ec", green: "#2e5c46", rust: "#a23c2a", dark: "#15130c", cream: "#f0ece0" };
const clamp = (v: number) => Math.max(0, Math.min(1, v));

function FilmScore() {
  const events: { at: number; note: number; volume: number; ring: number; pan: number }[] = [];
  const chords = [[146.83,220,261.63,329.63,440],[130.81,196,261.63,349.23,440],[174.61,261.63,349.23,440,523.25],[130.81,196,261.63,329.63,523.25]];
  const contour = [0,2,1,3,2,4,1,3];
  let at = 8, i = 0;
  const actionFrames = [350, 450, 550];
  while (at < 925) {
    if (actionFrames.some((f) => Math.abs(f - at) < 7)) at += 9;
    const p = at / 925;
    const gap = Math.round(interpolate(p, [0,1], [28,11], { easing: Easing.inOutCubic }));
    const chord = chords[Math.floor(i / 12) % chords.length];
    const note = chord[contour[i % contour.length] % chord.length] * (p > .72 && i % 7 === 4 ? 2 : 1);
    const human = (Math.sin(i * 91.73 + .37) * 43758.5453) % 1;
    events.push({ at, note, volume: (.035 + p * .035) * (.82 + Math.abs(human) * .18), ring: 2.25 - p * .75, pan: -.2 + contour[i % contour.length] / 10 });
    at += gap + Math.round(human * 1.4) + (i % 8 === 7 ? Math.round(18 - p * 8) : 0); i++;
  }
  return <>{events.map((n,index)=><FeltPiano key={index} {...n} spread={.08} reverb={.48} detune={[-1.2,.7,-.4,1][index%4]} name={`score-${index}`}/>)}
    {[18,34,51,70].map((f,i)=><DeskTap key={f} at={f} volume={.1} pitch={150-i*9} pan={i%2?.18:-.18} name={`paper-${i}`}/>)}
    <Typing text="Show me what could block this launch." at={120} cps={20} every={4} volume={.038}/>
    <DeskTap at={350} volume={.15} pitch={135} name="blocked"/><DeskTap at={450} volume={.12} pitch={165} name="owner"/><DeskTap at={550} volume={.14} pitch={185} name="agent-update"/>
    <Tone at={300} durationInFrames={170} freq="F5" wave="sine" attack={1.1} decay={.4} sustain={.7} release={1.4} partials={[[2,.12],[3,.07],[5,.04],[7,.025]]} cutoff={8000} spread={.22} reverb={.55} volume={.024} name="bowed-a"/>
    <Tone at={590} durationInFrames={250} freq="A5" wave="sine" attack={1.4} decay={.5} sustain={.65} release={1.7} partials={[[2,.12],[3,.065],[5,.035],[7,.02]]} cutoff={8000} spread={.28} reverb={.6} volume={.026} name="bowed-b"/>
    {[928,934,941,949].map((f,i)=><FeltPiano key={f} note={[174.61,261.63,329.63,392][i]} at={f} ring={5} volume={.058} pan={-.24+i*.16} spread={.1} reverb={.64} name={`resolve-${i}`}/>)}</>;
}

/** Intern's own palette: sustained strings, tuned wood, and chatter becoming rhythm. No piano. */
function InternScore(){const mallets=[[16,"D4",.08],[52,"A4",.07],[104,"C5",.075],[170,"F4",.07],[238,"C5",.085],[300,"A3",.09],[350,"C4",.08],[410,"F4",.09],[520,"D4",.08],[530,"A4",.055],[612,"F4",.08],[622,"C5",.055],[704,"A4",.085],[714,"E5",.06],[796,"C5",.09],[806,"G5",.06],[914,"F4",.07],[925,"C5",.06]] as const;return <>
  <BowedString note="D3" durationInFrames={250} volume={.026} attack={1.1} release={1.5} pan={-.18} reverb={.38} name="friday-low"/><BowedString note="A3" durationInFrames={250} volume={.018} attack={1.4} release={1.5} pan={.14} reverb={.4} name="friday-high"/>
  <BowedString note="F3" at={230} durationInFrames={290} volume={.024} attack={.8} release={1.4} pan={-.2} reverb={.42} name="site-low"/><BowedString note="C4" at={230} durationInFrames={290} volume={.02} attack={1} release={1.4} pan={.04} reverb={.44} name="site-mid"/><BowedString note="A4" at={250} durationInFrames={270} volume={.014} attack={1.2} release={1.4} pan={.2} reverb={.46} name="site-air"/>
  <BowedString note="C3" at={470} durationInFrames={445} volume={.027} attack={.7} release={1.6} pan={-.22} reverb={.4} name="chatter-low"/><BowedString note="G3" at={470} durationInFrames={445} volume={.021} attack={.9} release={1.6} pan={0} reverb={.44} name="chatter-mid"/><BowedString note="E4" at={500} durationInFrames={415} volume={.017} attack={1.1} release={1.6} pan={.22} reverb={.48} name="chatter-high"/>
  <BowedString note="F3" at={914} durationInFrames={205} volume={.038} attack={.45} release={2.2} pan={-.24} reverb={.58} name="resolve-low"/><BowedString note="C4" at={914} durationInFrames={205} volume={.032} attack={.5} release={2.2} pan={-.08} reverb={.6} name="resolve-mid"/><BowedString note="A4" at={920} durationInFrames={195} volume={.026} attack={.6} release={2.1} pan={.12} reverb={.62} name="resolve-high"/><BowedString note="E5" at={928} durationInFrames={185} volume={.018} attack={.7} release={2} pan={.25} reverb={.64} name="resolve-air"/>
  {mallets.map(([at,note,volume],i)=><Mallet key={at} at={at} note={note} volume={volume} ring={i<5?1.4:1.05} pan={[-.18,.12,-.08,.2][i%4]} reverb={.3} detune={[-1,.6,-.3,.8][i%4]} name={`wood-${i}`}/>)}
  <Typing text="Show me what could block this launch." at={120} cps={20} every={4} volume={.032}/>
  {[300,350,410,490,582,674,766].map((at,i)=><DeskTap key={at} at={at} volume={i<3?.11:.07} pitch={150+i*5} pan={i%2?.16:-.16} name={`action-${i}`}/>)}
  </>}

function FrozenDeck() {
  const frame=useFrame(), exit=progress(frame,86,24,Easing.inOutCubic), stale=progress(frame,42,9,Easing.outBack);
  return <div style={{position:"absolute",inset:0,background:C.dark,color:C.cream,opacity:1-exit,transform:`scale(${1+exit*.08})`}}>
    <div className="mono" style={{position:"absolute",left:118,top:86,color:"#a49d8b",fontSize:20,letterSpacing:".14em"}}>{frame<42?"FRIDAY":"TUESDAY"} · 09:14</div>
    <div style={{position:"absolute",left:170,top:180,width:1120,height:690,borderRadius:22,background:"#fbfaf5",color:C.ink,boxShadow:"0 48px 120px rgba(0,0,0,.5)",transform:`rotate(${-2+exit*2}deg)`}}>
      <div style={{padding:"54px 64px",borderBottom:`1px solid ${C.line}`,display:"flex",justifyContent:"space-between"}}><span className="mono" style={{fontSize:20,color:C.green,letterSpacing:".12em"}}>Q3 LAUNCH REVIEW</span><span className="mono" style={{fontSize:18,color:C.muted}}>updated Friday</span></div>
      <div style={{padding:"72px 68px"}}><div className="display" style={{fontSize:72}}>Launch readiness</div><div className="display" style={{fontSize:184,lineHeight:1,marginTop:28}}>82<span style={{fontSize:70}}>%</span></div>
        <div style={{width:820,height:20,borderRadius:20,background:"#e4e2d9",marginTop:36,overflow:"hidden"}}><div style={{width:"82%",height:"100%",background:C.green}}/></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:24,marginTop:54}}>{["Messaging ✓","Support ✓","Migration ✓"].map(x=><div key={x} style={{padding:22,border:`1px solid ${C.line}`,borderRadius:12,fontSize:24}}>{x}</div>)}</div>
      </div>
    </div>
    {frame>=42&&[["Support brief changed",1370,245,-3],["Owner left the team",1290,400,4],["Migration slipped",1390,555,-2]].map(([text,left,top,rot],i)=><div key={String(text)} style={{position:"absolute",left:Number(left),top:Number(top),width:400,padding:"24px 28px",borderRadius:14,background:i===1?"#f7e9e4":"#fff",color:C.ink,border:`2px solid ${i===1?C.rust:C.line}`,boxShadow:"0 24px 60px rgba(0,0,0,.3)",fontSize:26,transform:`translateX(${(1-stale)*180}px) scale(${stale}) rotate(${rot}deg)`,transformOrigin:"left center"}}>{text}</div>)}
    <div data-copy="" style={{position:"absolute",left:1360,top:740,width:430}}><div className="display" style={{fontSize:60,lineHeight:1.02,opacity:clamp((frame-8)/14)}}>This was true Friday.</div>{frame>=47&&<div className="mono" style={{marginTop:22,color:"#a9cbb6",fontSize:30}}>It’s Tuesday. Work moved.</div>}</div>
  </div>;
}

function AgentPrompt(){const frame=useFrame(),enter=progress(frame,108,24,Easing.outExpo),exit=progress(frame,224,22,Easing.inOutCubic),reply=progress(frame,178,18,Easing.outExpo);return <div style={{position:"absolute",inset:0,background:`linear-gradient(180deg,#fff,${C.wash})`,opacity:enter*(1-exit)}}>
  <Wordmark size={52} style={{position:"absolute",left:110,top:68}}/>
  <div style={{position:"absolute",left:250,top:180,width:1420,borderRadius:26,border:`1px solid ${C.line}`,background:C.paper,boxShadow:"0 40px 100px rgba(27,24,17,.14)",overflow:"hidden",transform:`translateY(${(1-enter)*80}px)`}}>
    <div style={{padding:"22px 30px",borderBottom:`1px solid ${C.line}`,display:"flex",alignItems:"center",gap:14}}><span style={{width:40,height:40,borderRadius:12,display:"grid",placeItems:"center",background:C.ink,color:C.cream,fontWeight:700}}>A</span><b style={{fontSize:24}}>Your agent</b><span style={{color:C.muted,fontSize:20}}>connected to Intern</span></div>
    <div style={{padding:"52px 48px 60px",minHeight:650}}><div style={{marginLeft:"auto",width:930,padding:"24px 30px",borderRadius:"22px 22px 6px 22px",background:C.ink,color:C.cream,fontSize:34,lineHeight:1.35}}><Typewriter text="Show me what could block this launch." at={120} cps={20} cursorAfter={false}/></div>
      {frame>=178&&<div style={{marginTop:44,fontSize:33,lineHeight:1.4,opacity:reply,transform:`translateY(${(1-reply)*24}px)`}}>Built it. Published it. Locked it to your company.<div style={{marginTop:22,display:"inline-flex",alignItems:"center",gap:16,padding:"20px 26px",borderRadius:14,background:"#f8faf8",border:`1px solid ${C.line}`}}><Dot/><span className="mono" style={{color:C.green,fontSize:30}}>launch.acme.tryintern.dev</span></div><div className="mono" style={{marginTop:18,color:C.muted,fontSize:22}}>One sentence → a working site</div></div>}
    </div>
  </div>
</div>}

function Activity({at,who,text,color,agent=false}:{at:number;who:string;text:string;color:string;agent?:boolean}){const frame=useFrame(),p=progress(frame,at,18,Easing.outExpo);return <div style={{marginTop:18,padding:"16px 17px",borderRadius:12,background:"#fff",border:`1px solid ${C.line}`,opacity:p,transform:`translateX(${(1-p)*30}px)`}}><div style={{display:"flex",gap:9,alignItems:"center",fontWeight:700,fontSize:18}}><span style={{width:28,height:28,borderRadius:8,background:agent?C.ink:color,color:"#fff",display:"grid",placeItems:"center",fontSize:13}}>{agent?"✦":who[0]}</span>{who}</div><div style={{marginTop:8,color:C.muted,fontSize:17,lineHeight:1.3}}>{text}</div></div>}

function TeamCursor({at,exitAt,name,color,from,to}:{at:number;exitAt:number;name:string;color:string;from:[number,number];to:[number,number]}){const frame=useFrame(),p=progress(frame,at,34,Easing.inOutCubic),out=progress(frame,exitAt,14,Easing.inCubic);if(frame<at||out>=1)return null;return <div style={{position:"absolute",left:interpolate(p,[0,1],[from[0],to[0]]),top:interpolate(p,[0,1],[from[1],to[1]]),zIndex:6,opacity:1-out,filter:"drop-shadow(0 3px 4px rgba(0,0,0,.2))"}}><svg width="28" height="34" viewBox="0 0 22 26"><path d="M2 2 L20 13 L11.5 14.5 L7 24 Z" fill={color} stroke="#fff" strokeWidth="1.5"/></svg><span style={{position:"absolute",left:22,top:19,padding:"4px 9px",borderRadius:6,background:color,color:"#fff",fontSize:15,fontWeight:700,whiteSpace:"nowrap"}}>{name}</span></div>}

function ProofWords(){const frame=useFrame();return <div data-copy="" style={{position:"absolute",left:1320,top:260,width:500}}>{[["Live data.",710],["Company sign-in.",770],["People + agents, together.",830]].map(([text,at])=>{const p=progress(frame,Number(at),22,Easing.outExpo);return <div key={String(text)} className="display" style={{fontSize:57,lineHeight:1.05,marginBottom:38,opacity:p,transform:`translateY(${(1-p)*26}px)`,color:String(text).startsWith("People")?C.green:C.ink}}>{text}</div>})}</div>}

function LaunchRoom(){const frame=useFrame(),enter=progress(frame,238,32,Easing.outExpo),proof=progress(frame,450,30,Easing.inOutCubic),fade=progress(frame,486,22,Easing.inCubic),blocked=progress(frame,300,16,Easing.outExpo),claimed=progress(frame,350,18,Easing.outExpo),fixed=progress(frame,410,22,Easing.outExpo);const readiness=fixed>0?Math.round(interpolate(fixed,[0,1],[80,89])):claimed>0?Math.round(interpolate(claimed,[0,1],[76,80])):Math.round(interpolate(blocked,[0,1],[82,76]));const impact=progress(frame,300,7,Easing.outBack)*(1-progress(frame,324,14,Easing.inOutCubic));return <div style={{position:"absolute",inset:0,background:`linear-gradient(180deg,rgba(162,60,42,${impact*.12}),${C.wash})`,opacity:enter*(1-fade)}}>
  <div style={{position:"absolute",left:110,top:72,width:1700,transform:`translate(${interpolate(proof,[0,1],[0,-330])}px,${interpolate(proof,[0,1],[0,42])}px) scale(${interpolate(proof,[0,1],[1,.68])})`,transformOrigin:"top center"}}>
    <div style={{position:"relative",borderRadius:22,border:`1px solid ${impact>.1?C.rust:C.line}`,background:C.paper,boxShadow:`0 42px 110px rgba(${impact>.1?"162,60,42":"27,24,17"},.18)`,overflow:"hidden",transform:`scale(${.18+enter*.82+impact*.018}) rotate(${impact*-.35}deg)`,transformOrigin:"50% 17%"}}>
      <div style={{height:70,padding:"0 26px",display:"flex",alignItems:"center",borderBottom:`1px solid ${C.line}`,background:"#fafaf8"}}><div style={{display:"flex",gap:9}}>{[0,1,2].map(i=><span key={i} style={{width:12,height:12,borderRadius:99,background:"#deddd6"}}/>)}</div><div className="mono" style={{marginLeft:22,fontSize:20,color:C.muted,display:"flex",alignItems:"center",gap:9}}><LockGlyph/> launch.acme.tryintern.dev</div><div className="mono" style={{marginLeft:"auto",color:C.green,fontSize:16}}>● LIVE · INTERNAL</div></div>
      <div style={{padding:"42px 48px 48px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div data-copy=""><div className="mono" style={{color:C.green,fontSize:18,letterSpacing:".12em"}}>LAUNCH ROOM</div><div className="display" style={{fontSize:68,marginTop:8}}>What could block Tuesday?</div></div><div style={{textAlign:"right"}}><div className="display" style={{fontSize:100,lineHeight:1}}>{readiness}<span style={{fontSize:40}}>%</span></div><div style={{color:C.muted,fontSize:18}}>ready to launch</div></div></div>
        <div style={{position:"relative",height:12,borderRadius:99,background:"#e7e6df",marginTop:28,overflow:"visible"}}><div style={{width:`${readiness}%`,height:"100%",borderRadius:99,background:readiness<80?C.rust:C.green,boxShadow:fixed>0?`0 0 ${18*fixed}px rgba(46,92,70,.45)`:"none"}}/>{fixed>0&&<span style={{position:"absolute",left:`calc(${readiness}% - 8px)`,top:-4,width:20,height:20,borderRadius:99,background:C.green,transform:`scale(${.6+fixed*.4})`,boxShadow:"0 0 0 8px rgba(46,92,70,.12)"}}/>}</div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 390px",gap:32,marginTop:36}}><div style={{border:`1px solid ${C.line}`,borderRadius:16,overflow:"hidden"}}><div className="mono" style={{display:"grid",gridTemplateColumns:"1.2fr .7fr .8fr",padding:"15px 22px",background:"#fafaf8",color:C.muted,fontSize:15}}><span>WORKSTREAM</span><span>OWNER</span><span>STATUS</span></div>
          {[["Release notes","Mara","Ready"],["Pricing switch","Jon","Ready"],["Support brief",claimed>.5?"Priya":"—",blocked>.5&&fixed<.5?"Blocked":fixed>.5?"Agent cleared":"Watch"],["Incident cover","Owen","Ready"]].map(([task,owner,status],i)=><div key={task} style={{display:"grid",gridTemplateColumns:"1.2fr .7fr .8fr",alignItems:"center",padding:"20px 22px",borderTop:`1px solid ${C.line}`,fontSize:23,background:i===2&&blocked>.5&&fixed<.5?"rgba(162,60,42,.055)":i===2&&fixed>0?`rgba(169,203,182,${.08+.22*fixed})`:"#fff",transform:i===2&&fixed>0?`translateX(${(1-fixed)*18}px) scale(${1+Math.sin(fixed*Math.PI)*.018})`:undefined,boxShadow:i===2&&fixed>0?`inset 5px 0 0 ${C.green}`:undefined}}><b>{task}</b><span style={{color:owner==="—"?C.rust:C.muted}}>{owner}</span><span style={{justifySelf:"start",padding:"6px 12px",borderRadius:99,background:status==="Blocked"?"#f5dfd8":"#e4f0e8",color:status==="Blocked"?C.rust:C.green,fontSize:17,fontWeight:700}}>{status}</span></div>)}</div>
          <aside style={{border:`1px solid ${C.line}`,borderRadius:16,padding:24,background:"#fafaf8"}}><div style={{display:"flex",alignItems:"center",gap:10,fontWeight:700,fontSize:20}}><Dot size={10}/> Live activity</div>{frame>=306&&<Activity at={306} who="Sam" text="Marked Support brief blocked" color={C.rust}/>} {frame>=356&&<Activity at={356} who="Priya" text="Added herself as owner" color={C.green}/>} {frame>=416&&<Activity at={416} who="Alex’s agent" text="Updated checklist · cleared blocker" color={C.green} agent/>}</aside>
        </div>
      </div>
      <TeamCursor at={276} exitAt={336} name="Sam" color={C.rust} from={[1390,690]} to={[850,545]}/>
      <TeamCursor at={330} exitAt={396} name="Priya" color={C.green} from={[1420,730]} to={[790,545]}/>
    </div>
  </div>
</div>}

const SITE_REQUESTS = [
  { who:"Mara", ask:"Can someone map this repo before migration?", title:"Codebase Map", kind:"map", color:"#2e5c46" },
  { who:"Jon", ask:"How’s review load trending this week?", title:"Engineering Pulse", kind:"pulse", color:"#207b78" },
  { who:"Sam", ask:"What could still block launch?", title:"Launch Room", kind:"launch", color:"#a86e12" },
  { who:"Priya", ask:"Can we capture friction from user sessions?", title:"Friction Log", kind:"friction", color:"#a23c2a" },
] as const;

function MiniSite({kind,color}:{kind:string;color:string}){if(kind==="map")return <svg width="100%" height="150" viewBox="0 0 360 150">{[[55,72],[170,35],[175,112],[300,74]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="18" fill="#fff" stroke={color} strokeWidth="3"/><circle cx={x} cy={y} r="5" fill={color}/></g>)}<path d="M73 67L151 40M72 80l84 27m38-67 88 29m-88 41 88-29" fill="none" stroke="#b8b7b0" strokeWidth="3" strokeDasharray="7 6"/></svg>;if(kind==="pulse")return <div style={{height:150,display:"flex",alignItems:"end",gap:13,padding:"20px 18px"}}>{[.35,.62,.48,.82,.7,.92,.66].map((h,i)=><span key={i} style={{height:`${h*100}%`,flex:1,borderRadius:"6px 6px 2px 2px",background:i===5?color:"#c7dcda"}}/>)}</div>;if(kind==="launch")return <div style={{height:150,padding:18}}><div style={{height:8,borderRadius:9,background:"#deddd7"}}><div style={{width:"89%",height:"100%",background:color,borderRadius:9}}/></div>{["Release notes","Support brief","Migration"].map(x=><div key={x} style={{display:"flex",justifyContent:"space-between",padding:"10px 2px",borderBottom:`1px solid ${C.line}`,fontSize:15}}><span>{x}</span><b style={{color:C.green}}>Ready</b></div>)}</div>;return <div style={{height:150,display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,padding:16}}>{["Replay","Issue","Owner","Good","Fix","Done"].map((x,i)=><div key={x} style={{borderRadius:7,background:i===1?"#f4dfd7":i===4?"#f8e9b9":"#e8eee9",display:"grid",placeItems:"center",fontSize:14,color:i===1?C.rust:C.ink}}>{x}</div>)}</div>}

function ChatterSites(){const frame=useFrame(),enter=progress(frame,472,28,Easing.outExpo),exit=progress(frame,914,24,Easing.inCubic);return <div style={{position:"absolute",inset:0,background:"linear-gradient(180deg,#fff,#f3f2ec)",opacity:enter*(1-exit)}}><div style={{position:"absolute",left:90,top:76,width:1740}}><div className="mono" style={{fontSize:18,color:C.green,letterSpacing:".13em"}}>THE REQUESTS WERE ALREADY IN THE ROOM</div><div className="display" style={{fontSize:74,marginTop:12}}>Turn the ask into a site.</div></div><div style={{position:"absolute",left:100,top:245,width:680}}>{SITE_REQUESTS.map((s,i)=>{const at=490+i*92,p=progress(frame,at,22,Easing.outExpo);return <div key={s.title} style={{display:"flex",alignItems:"flex-start",gap:14,marginBottom:24,opacity:p,transform:`translateX(${(1-p)*-40}px)`}}><span style={{width:42,height:42,borderRadius:12,background:s.color,color:"#fff",display:"grid",placeItems:"center",fontWeight:700}}>{s.who[0]}</span><div><b style={{fontSize:20}}>{s.who}</b><div style={{marginTop:5,padding:"13px 17px",borderRadius:"6px 18px 18px 18px",background:"#fff",border:`1px solid ${C.line}`,fontSize:22,boxShadow:"0 10px 28px rgba(27,24,17,.07)"}}>{s.ask}</div></div></div>})}</div><div style={{position:"absolute",left:850,top:225,width:970,display:"grid",gridTemplateColumns:"1fr 1fr",gap:22}}>{SITE_REQUESTS.map((s,i)=>{const at=530+i*92,p=progress(frame,at,28,Easing.outBack);return <div key={s.title} style={{borderRadius:16,background:"#fff",border:`1px solid ${C.line}`,boxShadow:"0 22px 55px rgba(27,24,17,.12)",overflow:"hidden",opacity:p,transform:`translateY(${(1-p)*60}px) scale(${.88+p*.12})`}}><div style={{height:42,padding:"0 14px",display:"flex",alignItems:"center",gap:6,background:"#fafaf8",borderBottom:`1px solid ${C.line}`}}><span style={{width:7,height:7,borderRadius:9,background:s.color}}/><span className="mono" style={{fontSize:12,color:C.muted}}>built with Intern</span></div><MiniSite kind={s.kind} color={s.color}/><div style={{padding:"14px 18px 17px",borderTop:`1px solid ${C.line}`}}><b style={{fontSize:23}}>{s.title}</b><div className="mono" style={{fontSize:12,color:C.green,marginTop:5}}>{s.title.toLowerCase().replaceAll(" ","-")}.acme.tryintern.dev</div></div></div>})}</div>{frame>=850&&<div data-copy="" className="display" style={{position:"absolute",left:100,bottom:62,fontSize:46,color:C.green,opacity:progress(frame,850,24,Easing.outExpo)}}>One sentence each. Live for everyone who needs it.</div>}</div>}

function EndCard(){const frame=useFrame(),p=progress(frame,946,42,Easing.inOutCubic),black=progress(frame,1110,30,Easing.inCubic);return <div style={{position:"absolute",inset:0,background:C.paper,opacity:p}}><Img src={staticFile("cascade-range.webp")} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",filter:"grayscale(1) contrast(.8)",opacity:.18,transform:`scale(${1.07-p*.07})`}}/><div style={{position:"absolute",inset:0,background:"linear-gradient(180deg,rgba(255,255,255,.35),#fff 90%)"}}/><div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><Wordmark size={84}/><div data-copy="" className="display" style={{marginTop:52,fontSize:154,lineHeight:.91,textAlign:"center",letterSpacing:"-.03em"}}>Send a site,<br/><em style={{color:C.green}}>not a deck.</em></div><div className="mono" style={{marginTop:48,fontSize:36,color:C.green}}>tryintern.dev</div><div style={{marginTop:20,color:C.muted,fontSize:22}}>Start free · No card required</div></div><div style={{position:"absolute",inset:0,background:"#000",opacity:black}}/></div>}

function FinalCard(){const frame=useFrame(),wipe=progress(frame,914,36,Easing.inOutCubic),copy=progress(frame,942,28,Easing.outExpo),black=progress(frame,1110,30,Easing.inCubic);if(frame<914)return null;return <div style={{position:"absolute",inset:0,background:"radial-gradient(80% 90% at 50% 30%,#fff 0%,#f5f4ee 100%)",clipPath:`inset(${(1-wipe)*100}% 0 0 0)`}}><div style={{position:"absolute",left:interpolate(wipe,[0,1],[110,720]),top:interpolate(wipe,[0,1],[238,700]),width:interpolate(wipe,[0,1],[1450,480]),height:8,borderRadius:99,background:C.green,boxShadow:"0 8px 30px rgba(46,92,70,.22)"}}/><div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",opacity:copy,transform:`translateY(${(1-copy)*42}px)`}}><Wordmark size={84}/><div data-copy="" className="display" style={{marginTop:48,fontSize:154,lineHeight:.91,textAlign:"center",letterSpacing:"-.03em"}}>Send a site,<br/><em style={{color:C.green}}>not a deck.</em></div><div className="mono" style={{marginTop:58,fontSize:36,color:C.green}}>tryintern.dev</div><div style={{marginTop:20,color:C.muted,fontSize:22}}>Start free · No card required</div></div><div style={{position:"absolute",inset:0,background:"#000",opacity:black}}/></div>}

export function InternFilm(){return <AbsoluteFill className="promo" style={{background:C.dark}}><InternScore/><FrozenDeck/><AgentPrompt/><LaunchRoom/><ChatterSites/><FinalCard/></AbsoluteFill>}
