export const BEATS = [
  {
    id: "intro",
    chapter: "LEVEL 0 / INTUITION",
    title: "Why give a model another pass?",
    subtitle: "First, a small story about connecting information.",
    text: "Lea hands a key to Omar. Omar puts it in a drawer. Where is the key? Answering means joining the two facts. Keep that tiny story in mind. It will guide us from the basic idea all the way down to the math.",
  },
  {
    id: "whole",
    chapter: "LEVEL 0 / INTUITION",
    title: "Read. Refine. Answer.",
    subtitle: "The whole idea, from beginning to end.",
    text: "The model reads the story, builds an internal representation, refines that representation, and produces an answer. Here, the answer is drawer. A recurrent Transformer reuses a processing step to revise its internal state. It is revising numerical representations, not writing and rereading a visible draft answer.",
  },
  {
    id: "refine",
    chapter: "LEVEL 0 / INTUITION",
    title: "Same information. More chances to connect it.",
    subtitle: "A conceptual illustration, not a trace of trained activations.",
    text: "Imagine first identifying the key and the people. Then connecting the handoff. Then connecting the key to its final location. This is an intuition for refinement, not a claim about what a particular model thinks on each pass. Repetition creates an opportunity to combine information; improvement is not guaranteed.",
  },
  {
    id: "architecture",
    chapter: "LEVEL 1 / THE WHOLE MODEL",
    title: "The Universal Transformer",
    subtitle: "Dehghani et al. · 2018 preprint / ICLR 2019",
    text: "Now open the model. The original Universal Transformer has an encoder and a decoder. The encoder refines representations of the input. The decoder refines the available output prefix while consulting the encoder; masking hides future output tokens. A projection and softmax produce probabilities, from which we select the next token. Repeat the decoder process to produce the answer.",
  },
  {
    id: "axes",
    chapter: "LEVEL 1 / THE WHOLE MODEL",
    title: "Recurrence runs down depth, not along the sentence",
    subtitle: "All token representations are revised in parallel at each depth step.",
    text: "There are two different directions here. Across the page are token positions. Down the page are refinement steps. At each depth step, all positions are revised in parallel. The encoder reuses its weights across steps. The decoder does the same with its own weights. Generating output tokens is a separate, autoregressive process.",
  },
  {
    id: "step",
    chapter: "LEVEL 2 / ONE REVISION",
    title: "Exchange information. Transform it. Repeat.",
    subtitle: "Zoom into one encoder refinement step.",
    text: "Follow one revision from start to finish. Add position and depth signals to the current state. Self-attention exchanges information across positions. A transition function then transforms each position. Residual connections and normalization surround these operations. The resulting state becomes the input to the next revision.",
  },
  {
    id: "attention",
    chapter: "LEVEL 2 / ONE REVISION",
    title: "Attention lets each position consult the others",
    subtitle: "Queries ask, keys match, values contribute.",
    text: "Inside attention, each position produces a query, a key, and a value. Queries and keys produce matching scores. Softmax turns those scores into mixing weights. A weighted sum of values gives each position information from the others. Multiple heads do this in parallel. The result is an updated representation, not an answer word.",
  },
  {
    id: "transition",
    chapter: "LEVEL 2 / ONE REVISION",
    title: "One shared rule acts on new states",
    subtitle: "Position-wise feed-forward transition shown; the paper also uses separable convolution.",
    text: "The feed-forward version applies a projection, a nonlinear gate, and another projection at each position. The same learned rules are reused, but the incoming values change. Position signals say where a token is; depth signals say which refinement step this is. Shared weights therefore do not imply identical computation results.",
  },
  {
    id: "return",
    chapter: "LEVEL 2 / BACK TO THE WHOLE",
    title: "Now run the complete model again",
    subtitle: "The pieces serve the same input-to-answer journey.",
    text: "Return to our story. The encoder repeatedly exchanges and transforms information about the key. The decoder consults that refined input while processing the available answer prefix. The prediction layer assigns probabilities to the next token. Selecting drawer completes this illustrative answer. Every inner step supports that outer journey.",
  },
  {
    id: "halting",
    chapter: "LEVEL 2 / AN OPTIONAL VARIANT",
    title: "Different positions can use different depths",
    subtitle: "Adaptive Computation Time is a learned stopping mechanism.",
    text: "The paper also includes optional dynamic halting. Different positions can stop updating after different numbers of steps. This is learned control over computation, not a detector that an answer is true. For the training explanation that follows, we will use a fixed number of refinement steps so the gradient paths stay clear.",
  },
  {
    id: "train",
    chapter: "LEVEL 3 / THE WHOLE LEARNING LOOP",
    title: "Predict → compare → backpropagate → update",
    subtitle: "Explain the learning loop before opening the calculus.",
    text: "How does the model learn useful refinements? During training, it predicts token probabilities, compares the probability assigned to the correct target, and computes a loss. Backpropagation carries loss sensitivity backward through the decoder and encoder. The optimizer uses those gradients to adjust the weights. On the next example, the entire process runs again.",
  },
  {
    id: "unroll",
    chapter: "LEVEL 3 / THE WHOLE LEARNING LOOP",
    title: "One block appears at every refinement step",
    subtitle: "Draw repeated uses separately; keep their parameters tied.",
    text: "To see the gradient paths, draw each use of a recurrent block separately. These are uses of the same weights, not independent copies. A later state depends on an earlier state, so feedback passes backward through that dependency. Every use also contributes feedback about the shared parameters. Those contributions must be added.",
  },
  {
    id: "nudge",
    chapter: "LEVEL 4 / ONE LOCAL DERIVATIVE",
    title: "A tiny nudge explains one gradient",
    subtitle: "A teaching example inside a linear projection.",
    text: "Take one connection. The input is three and the weight is one half, so the output is one point five. The target is one. For half squared error, the output gradient is one half. A weight nudge is amplified by the input, three. Multiply: the weight gradient is one point five.",
  },
  {
    id: "projection",
    chapter: "LEVEL 4 / MANY LOCAL CONNECTIONS",
    title: "A matrix is a bank of input mixers",
    subtitle: "Set up the complete local calculation before differentiating it.",
    text: "A matrix is many such connections. Each row combines inputs to produce one output. Our two by two example maps three and one to five and negative two. Then a gradient comes back from the rest of the network. Call that vector g. Now we can compute all the connection gradients.",
  },
  {
    id: "matrix",
    chapter: "LEVEL 4 / MATRIX BOOKKEEPING",
    title: "The same rule fills a whole gradient matrix",
    subtitle: "For y = Wx, let g be the gradient arriving from the loss.",
    text: "Now give the projection several inputs and outputs. Every weight gradient is its input value times the gradient at its output. An outer product writes all those values at once: g times x transpose. To continue backward to the inputs, sum the contributions through each connection. That gives W transpose times g.",
  },
  {
    id: "calculus",
    chapter: "LEVEL 4 / WHY THE MATRICES LOOK THAT WAY",
    title: "Two ways to change the output",
    subtitle: "Change the weights, or change the incoming state.",
    text: "The calculus says the same thing. A tiny output change is the weight change acting on x, plus W acting on the input change. Dot that with the incoming gradient g. Collect the coefficients of the independent weight and input changes. They are exactly the outer product and the transposed matrix product we just drew.",
  },
  {
    id: "sum",
    chapter: "LEVEL 4 / RECONNECT TO THE LOOP",
    title: "Route backward. Add across uses. Update once.",
    subtitle: "Local matrix rules compose into backpropagation through recurrent depth.",
    text: "Inside a full block, these local rules combine into a Jacobian: a table of local sensitivities. Its transpose carries the state gradient backward. Add each use's parameter contribution to get the gradient for the shared block. Only then does the optimizer update that one parameter set. Training embeddings and other blocks receive their own gradients too.",
  },
  {
    id: "end",
    chapter: "BACK TO LEVEL 0",
    title: "Reuse the rule. Refine the representation.",
    subtitle: "The same end-to-end story, now with the pieces understood.",
    text: "We started with a story and an answer. In between, the model repeatedly refines internal representations, then decodes a prediction. Training teaches those shared refinement rules through the same chain rule used elsewhere in neural networks. More steps cost computation, and do not guarantee better answers. That is the idea of recurrent depth.",
  },
] as const;
